### ISSUE TITLE
retool-temporal-services-helm does not template/render correctly.

### ISSUE THREAD

**Issue by Justin-DynamicD** [tryretool/retool-helm#167]
## details

retool chart version: 6.2.0
helm version: v3.13.3

## demo

simply download the example values.yaml file and make the following adjustments:

```Yaml
retool-temporal-services-helm:
  enabled: true
  server:
    image:
      repository: tryretool/one-offs
      tag: retool-temporal-1.1.5
      pullPolicy: IfNotPresent
    useLegacyHealthProbe: false
    config:
      persistence:
        default:
          sql:
            host: dummy.endpoint.com
            port: 5432
            database: temporal
            user: testuser
            password: password
        visibility:
          sql:
            host: dummy.endpoint.com
            port: 5432
            database: temporal_visibility
            user: testuser
            password: password
```
Once you have your values file you can render the template wit ha simple:

```Shell
helm template example retool/retool -f valuest.yaml --version 6.2.0
```

## Result

While the chart does render, trwo warnings are displayed and the temporal values do not get properly passed to the containers, reverting to the default values:

```Shell
retool/factory-sit.yaml --version 6.2.0
coalesce.go:286: warning: cannot overwrite table with non table for retool.retool-temporal-services-helm.server.config.persistence.default.sql (map[database:temporal driver:postgres host:_HOST_ maxConnLifetime:1h maxConns:20 password:_PASSWORD_ port:5432 user:_USERNAME_])
coalesce.go:286: warning: cannot overwrite table with non table for retool.retool-temporal-services-helm.server.config.persistence.visibility.sql (map[database:temporal_visibility driver:postgres host:_HOST_ maxConnLifetime:1h maxConns:20 password:_PASSWORD_ port:5432 user:_USERNAME_])
```

Looks like a formatting issue but can't seem to find it.
