### ISSUE TITLE
Incorrect Secrets usage

### ISSUE THREAD

**Issue by rjop-hccgt** [tryretool/retool-helm#210]
I am creating specific plain kubernetes secrets to hold the different values required for the database, retool license, encryption and jwt values required by retool. However even if I specify that I don't want to use the secrets, it seems that this isn't possible in the current helm chart. For example:
```yaml
config:
  licenseKeySecretName: retool-licence
  licenseKeySecretKey: licence-key
  useInsecureCookies: false
  encryptionKeySecretName: retool-encryption-key
  encryptionKeySecretKey: encryption-key

  postgresql:
    passwordSecretName: retool-db-credentials
    passwordSecretKey: password
postgresql:
    enabled: false
externalSecrets:
  enabled: true
  externalSecretsOperator:
    enabled: false
    useLegacyCR: false
  includeConfigSecrets: false
```
This generates the following deployment which doesn't include the secrets I've specified :
```yaml
# Reduced for brevity:
        env:
          - name: DEPLOYMENT_TEMPLATE_TYPE
            value: "k8s-helm"
          - name: DEPLOYMENT_TEMPLATE_VERSION
            value: "6.3.4"
          - name: NODE_ENV
            value: production
          - name: SERVICE_TYPE
            value: MAIN_BACKEND,DB_CONNECTOR,DB_SSH_CONNECTOR
          
          - name: CLIENT_ID
            value: ''
          - name: COOKIE_INSECURE
            value: "false"
          - name: POSTGRES_HOST
            value: "<REDACTED>"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "<REDACTED>"
          - name: POSTGRES_USER
            value: "<REDACTED>"
          - name: POSTGRES_SSL_ENABLED
            value: "false"
          
        envFrom:
        - secretRef:
            name: retool-config


```

It seems that the helm chart is trying to create the secrets no matter what: https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/secret.yaml#L1
I believe the conditions to create the secret and inject them into the deployments are incorrect as they are never included in either deployment:
https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_backend.yaml#L156-L207
I think the correct logic should be if either the config.postgresl.passwordSecretName is not empty or the `shouldIncludeConfigSecretsEnvVars` is `1` the values should be injected.

I do believe this relates to [this](https://github.com/tryretool/retool-helm/issues/83)
