### ISSUE TITLE
Ingress error while using apiVersion: networking.k8s.io/v1

### ISSUE THREAD

**Issue by muninn-huginn** [tryretool/retool-helm#29]
Hi,

I'm trying to deploy retool with ingress in my cluster (EKS) using the snippet below to override the ingress section in the values yaml, when I use port forwarding retool works as expected.

```yaml
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: retool
    labels:
      app.kubernetes.io/name: retool
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: ****
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
  spec:
    rules:
      - host: "dev-retool.***.***"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: retool
                  port:
                    number: 3000
```

I receive the following error,
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```

Any suggestions?
