### ISSUE TITLE
Feature Request: Add support for optionally passing in environment variable blocks

### ISSUE THREAD

**Issue by alanquillin** [tryretool/retool-helm#32]
Currently, you can only pass in extra environment variables as key value pairs in the values file:

```
env:
    foo: bar
```

however, this does not help if you need to pass in variables from config maps or secrets.  It would be super helpful to be able to add something like the following to the values:

```
extraEnvs:
- name: SECRET_USERNAME
   valueFrom:
      secretKeyRef:
        name: mysecret
        key: username
``` 

The only way I have found is to create a secret and add it as the `externalSecrets`, however, this then requires me to manage ALL the environment variables for all the secrets, which is not ideal.
