### ISSUE TITLE
question: extraContainers value

### ISSUE THREAD

**Issue by hakuno** [tryretool/retool-helm#42]
Hey, there!

I need to add one "sidecar" or more on helm release. I found it has `extraContainers` available.

Is that the best place to put my sidecars? Is that designed for this?

```
{{- with .Values.extraContainers }}
{{ tpl . $ | indent 6 }}
{{- end }}
```

I can pass a list of multine strings and it will understand variables as well. Am I right?

Cheers!

**Comment by hakuno** [comment]
It works.

**Comment by guissalustiano** [comment]
For those who had trouble using that, you need to pass it as a string:
```yaml
extraContainers: |+
  - name: cloud-sql-proxy
    image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.12.0"
    args:
      - "--private-ip"
      - "--max-sigterm-delay=30s"
      - "project.region:db?port=6000"
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        memory: "128Mi"
        cpu:    "10m"
      limits:
        memory: "512Mi"
        cpu:    "100m"
    volumeMounts:
      - mountPath: "/keys.json"
        name: credentials
        readOnly: true

extraVolumes: 
- name: credentials
  secret:
    secretName: cloudsql-all-client
```
