### ISSUE TITLE
Cannot bump Retool version

### ISSUE THREAD

**Issue by kentwalters** [tryretool/retool-helm#6]
With this Helm chart we can’t currently bump the Retool version as it is specified in the chart itself and not an editable value.

**Comment by kyle-retool** [comment]
> and not an editable value

I believe that this actually is a configurable value. In `values.yaml`:

```yaml
image:
  repository: "tryretool/backend"
  tag: "latest"
  pullPolicy: "IfNotPresent"
```

So I think if you add the following to the values file passed into `helm install`, you should be able to set the version.

```yaml
image:
  tag: "2.66.14"
```
